### PR TITLE
UI Improvements: Improved Animations & Blur, Fixed Notch Shape, and more!

### PR DESCRIPTION
**Pull request by OmChachad**
I've made a bunch of changes to make the experience for users significantly better! The Boring Notch Experience is now closer to that of the official Apple Dynamic Island on an iPhone. I think users will really appreciate these changes!

**The following are all the changes that have been made:**

- Updated Open/Close Animation to match iOS Behavior
- Added Blur Effect, and reduced existing blur delay to match iOS Behavior
- Album Artwork now shrinks, and reduces in opacity when media is paused.
- The playback slider is now more response to dragging, has a larger click target, and responds only to hovers.
- Increased Play Button Size relative to other buttons.
- Reduced the Artwork Glow size so that it no longer interferes with the physical notch, to ensure the physical notch stays as hidden as possible.
- Matched Artwork and Notch Corner Radius
- The Notch Shape is corrected to be perfectly symmetric and matches the physical notch closely. Previously, the shape was slightly jagged and did not perfectly fit the physical notch.
- Added Matched Geometry Effect to Spectrum
- Added Safe Area for Hover Zone: Added a 30px safe area around the notch to keep the notch from closing instantly as soon as the cursor exits.
- Reduced Padding Between Song Name and Artist Name

Preview: https://github.com/user-attachments/assets/55056829-7c6d-4f95-9a88-09326a2d5eff

### CODE REVIEW

**Comment by fofsinx** [comment]
Thanks for the contribution, but please share some preview. @OmChachad

**Comment by fofsinx** [comment]
Screenshot 2024-11-23 at 9 38 44 PM
@OmChachad bug

**Comment by OmChachad** [comment]
Checking this out! Added the preview!

**Comment by fofsinx** [comment]
@OmChachad Also try to add a sqash animation as song changes just like ios, that would be cool.

**Comment by richardkunkli** [comment]
Hey @OmChachad 
Great work. Really nice changes. Can you please check the matchedGeometryEffect of visualizer when Calendar and Mirror are turned off? It seems it has some issues with the transition on open.

**Comment by fofsinx** [comment]
also @richardkunkli let's rewrite the layout sometime. not sure when.

**Comment by richardkunkli** [comment]
Much needed, but not sure when will have time to make such a big change. It requires a whole new codebase.

**Comment by fofsinx** [comment]
> Much needed, but not sure when will have time to make such a big change. It requires a whole new codebase.

i'll do it in a day. LoL

**Comment by OmChachad** [comment]
> @OmChachad Also try to add a sqash animation as song changes just like ios, that would be cool.

Are you referring to the animation to the artwork when changing a song? Certainly possible, will work on that!

**Comment by fofsinx** [comment]
> > @OmChachad Also try to add a sqash animation as song changes just like ios, that would be cool.
> 
> Are you referring to the animation to the artwork when changing a song? Certainly possible, will work on that!

Yeah

**Comment by OmChachad** [comment]
> Thanks for the contribution, but please share some preview. @OmChachad

Added!

**Comment by OmChachad** [comment]
> Screenshot 2024-11-23 at 9 38 44 PM @OmChachad bug

Fixed!

**Comment by fofsinx** [comment]
@OmChachad rebase with dev.

**Comment by OmChachad** [comment]
> Hey @OmChachad Great work. Really nice changes. Can you please check the matchedGeometryEffect of visualizer when Calendar and Mirror are turned off? It seems it has some issues with the transition while opening.

Thanks! Can you share a recording of the issue please, I can't find any glitches when opening myself 😅

**Comment by fofsinx** [comment]
`git rebase origin/dev` then solve the merge conflicts.

**Comment by fofsinx** [comment]
@OmChachad wait let me fix the main and dev commit history!

**Comment by OmChachad** [comment]
> @OmChachad wait let me fix the main and dev commit history!

Okay let me know

**Comment by OmChachad** [comment]
> > > @OmChachad Also try to add a sqash animation as song changes just like ios, that would be cool.
> > 
> > 
> > Are you referring to the animation to the artwork when changing a song? Certainly possible, will work on that!
> 
> Yeah

Will work on this for a future PR!

**Comment by OmChachad** [comment]
> @OmChachad wait let me fix the main and dev commit history!

Excuse my naiveness, but I have no clue how to rebase in GitHub Desktop... Is there a different way to go about this?

**Comment by OmChachad** [comment]
Alright, I figured it out!! 🙌🏻

There's an issue with the hover animation though. Now, whenever the cursor is in the region of the physical notch, the Apple Music Icon slightly peaks from the bottom twice...

Screenshot 2024-11-24 at 4 02 07 PM

**Comment by OmChachad** [comment]
Nevermind. I just spent 30 minutes debugging a bug that never existed. I just had two instances of the app running at once, which caused that glitch...

All good now, ready to merge!

**Comment by OmChachad** [comment]
Hey, any update? 😃

**Comment by fofsinx** [comment]
I'll test it locally maybe today. @OmChachad been busy.

**Comment by OmChachad** [comment]
Done! I thought I did, but not sure what happened…

**Comment by fofsinx** [comment]
I updated the dev branch.

**Comment by OmChachad** [comment]
Fixed the compiling issue!

**Comment by fofsinx** [comment]
@OmChachad this is not ready for merge yet.

set this https://github.com/TheBoredTeam/boring.git as one of the remote 

run `git rebase remote/dev`

**Comment by fofsinx** [comment]
cc @richardkunkli

**Comment by albinkc** [comment]
hoping a git expert chimes in

**Comment by fofsinx** [comment]
Either @Alexander5015 or @OmChachad have to fix these conflicts.

**Comment by Alexander5015** [comment]
I don't see any conflicts, I think @richardkunkli is going to make a change when he has a chance and then he can merge it

**Comment by OmChachad** [comment]
yeah, I don't see any conflicts either; not really able to do anything here 😅

**Comment by fofsinx** [comment]
Closing this @OmChachad check the new PR here https://github.com/TheBoredTeam/boring.notch/pull/249

**Pull request closed without merging**
