### PR TITLE
added HoverButton component

### PR DESCRIPTION
**Pull request by Kraigo**
Added new component to support Hover effect on Mac.
Wrapper 3 media button into this new component.

### CODE REVIEW

**Comment by richardkunkli** [comment]
@Kraigo please attach a **Preview** to the pull request. It can be either a screenshot or a short screen recording.

**Comment by Kraigo** [comment]
Added attachment with demo @richardkunkli 
https://github.com/user-attachments/assets/c7d732bf-0e63-4fd5-bb0d-67deb42c3657

**Comment by richardkunkli** [comment]
So good, I really like that. Could you please change the destination to the panda-glow branch for this PR?

**Comment by Kraigo** [comment]
Hmm. I thought “Boring” was the main branch, and I made changes based on that branch.
What is the main branch? You’re naming it something quite creative, but it doesn’t make sense from a technical perspective.

**Comment by richardkunkli** [comment]
Sorry about that, that's our main branch. It's pretty straightforward. The reason I ask you to change it because we are preparing for a new release which is currently on a separate branch. The new release includes a literally rewritten codebase for all the features so it would cause conflicts.

**Comment by Kraigo** [comment]
Let me prepare new branch with my changes base on the panda-glows branch.

**Pull request closed without merging**
